### ISSUE TITLE
印象笔记的图标找不到，只出现一个evernote clipper

### ISSUE THREAD

**Issue by AcquireKnown** [hv0905/SaberColorfulStartmenu#12]
![image](https://user-images.githubusercontent.com/32730772/79119092-19e84000-7dc2-11ea-876e-83b3498fce4e.png)
![image](https://user-images.githubusercontent.com/32730772/79119114-27052f00-7dc2-11ea-929c-e218849ceadd.png)

**Comment by hv0905** [comment]
由于印象笔记的快捷方式为Windows Installer创建的受保护的快捷方式 （如图，无法导航到目标）
![image](https://user-images.githubusercontent.com/29349119/79121538-1bb50200-7dc8-11ea-87ca-d9e77bad1ecf.png)
此类快捷方式无法被应用识别并会被直接跳过，这个问题是无法避免的。  
目前唯一可行的解决办法是..手动删掉印象笔记的快捷方式然后找到其可执行文件并创建一个普通的快捷方式至开始菜单，这个快捷方式即可被应用读取并修改
目前此问题应该只会在印象笔记, Adobe Acrobat DC和老旧的office（2003？）等应用中存在（至少我没见过其它应用是这样的了..）

**Comment by AcquireKnown** [comment]
[image: image.png]谢谢你回复地这么及时，不过我就是找到这个exe程序然后右键固定到开始屏幕的，然而结果还是一样。

EdgeNeko <notifications@github.com> 于2020年4月13日周一 下午8:54写道：

**Comment by hv0905** [comment]
在修改EverNote Clipper后, 效果有被成功应用吗

**Comment by hv0905** [comment]
经测试, 通过shell右键固定到开始屏幕的图标是可以正常被修改的.

**Comment by AcquireKnown** [comment]
[image: image.png]
[image: image.png]没有应用，点过保存了，而且我的这个程序双击打开并没有什么用，仿佛是个假的。。。

EdgeNeko <notifications@github.com> 于2020年4月13日周一 下午10:28写道：

**Comment by AcquireKnown** [comment]
现在看是应用了，不过这个evernote clipper没什么用，双击不会弹出印象笔记
[image: image.png]

EdgeNeko <notifications@github.com> 于2020年4月13日周一 下午10:30写道：

**Comment by hv0905** [comment]
你检查下那个图标本身是不是正常的(目标路径等), 如果不正常是没法应用效果的😂,
另外可以检查下印象笔记exe目录是否有同名`.visualelementmanifest.xml`文件.

**Comment by AcquireKnown** [comment]
[image: image.png]我是直接找到对应程序双击没有任何反应，印象笔记是可以打开的
[image: image.png]然后的话你可以看到我把开始菜单里对应的起始位置也改到了程序所在的位置，还是识别不到这个应用

EdgeNeko <notifications@github.com> 于2020年4月13日周一 下午10:35写道：

**Comment by hv0905** [comment]
这个可能是windows shell或者应用的bug, 已经超出我们应用的能力范围了😂
另外github中邮件回复是不能附图的(除非使用markdown语法)

**Comment by AcquireKnown** [comment]
我一直没注意，是直接在gmail里回复的，我试试看重装下印象笔记吧，谢谢！

**Comment by AcquireKnown** [comment]
> 这个可能是windows shell或者应用的bug, 已经超出我们应用的能力范围了😂
> 另外github中邮件回复是不能附图的(除非使用markdown语法)
刚刚试了下重装并没有用。。。难道要让我放弃这么棒的应用嘛

**Comment by AcquireKnown** [comment]
打扰了，找到解决办法了，找到应用程序然后在桌面创建快捷方式，再将此快捷方式拖入到C:\ProgramData\Microsoft\Windows\Start
Menu\Programs这个文件夹里就可以识别到了

EdgeNeko <notifications@github.com> 于2020年4月13日周一 下午10:43写道：
