### ISSUE TITLE
我自己写的bat文件固定到开始菜单列表中刷不出来

### ISSUE THREAD

**Issue by Elijah-Neverdie** [hv0905/SaberColorfulStartmenu#13]
我自己写的bat文件固定到开始菜单的话，在saber's colorful start menu里面刷不到，请问有办法解决吗~

**Comment by hv0905** [comment]
完成  
现在应用可以切换所有类型的快捷方式对应的图标配置, 包括`exe, bat, cmd, ps1`, 甚至包括像`txt, docx`这样的非可执行文件.  
[**请在此处**](https://ci.appveyor.com/project/hv0905/sabercolorfulstartmenu/build/artifacts)下载最新非正式发布版本进行测试.  
已知问题: 非exe快捷方式在应用内显示的图标不是原本的图标, 而是`?`, 这个实在太难弄了, 就这样吧...
