### ISSUE TITLE
系统更新后图标失效

### ISSUE THREAD

**Issue by 3zeroed** [hv0905/SaberColorfulStartmenu#17]
![image](https://user-images.githubusercontent.com/44516212/139771857-8dd5e681-fad4-4ac2-9a21-8db5559dc885.png)

再进行修改也不起作用

**Comment by hv0905** [comment]
请问是颜色自定义失效还是图标自定义失效?
若为颜色自定义失效, 请参考[DEPRECATED](https://github.com/hv0905/SaberColorfulStartmenu#deprecated)

另: 如果真的有修改图标颜色的需求, 可以考虑用一个纯色背景的图片叠加应用图标设置为自定义图标
