### ISSUE TITLE
win10 1909有些程序磁贴颜色修改无效

### ISSUE THREAD

**Issue by zerohaunt** [hv0905/SaberColorfulStartmenu#9]
win10升到1909后,有些程序磁贴修改后没变化,像`印象笔记`和`telegram`改了都没反应
![image](https://user-images.githubusercontent.com/30367033/70400970-74fed480-1a68-11ea-9d6b-46689072ae9b.png)

**Comment by hv0905** [comment]
抱歉,我之前在忙期末
问题解决了吗 @tanglinghan

**Comment by zerohaunt** [comment]
tg是我改错图标了才没反应,不过印象笔记改了没效果,不过问题也不大,我不用印象了0.0.感谢大佬回复,啊哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"EdgeNeko"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 晚上6:44
收件人:&nbsp;"hv0905/SaberColorfulStartmenu"<SaberColorfulStartmenu@noreply.github.com&gt;;
抄送:&nbsp;"linghan"<im.linghan@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hv0905/SaberColorfulStartmenu] win10 1909有些程序磁贴颜色修改无效 (#9)




抱歉,我之前在忙期末
 问题解决了吗 @tanglinghan
